pipeline {
    agent any

    environment {
        PROJECT_PATH = 'Java/choon-java'
    }

    stages {
        stage('Pull Codes from GitHub') {
            steps{
                checkout scm
            }
        }
        stage('Build Codes by Gradle') {
            steps {
                sh """
                cd ${env.PROJECT_PATH}
                pwd
                """
            }
        }
    }
}